AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - config/*.rb
    - 'lib/language/*.rb'
    - 'lib/data_structures/practice.rb'

Metrics/LineLength:
  Max: 120
Metrics/PerceivedComplexity:
  Max: 15
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - 'spec/**/*.rb'
    - 'spec/**/**/*.rb'
    - 'Gemfile'
Metrics/MethodLength:
  Max: 30
Style/AsciiComments:
  Enabled: false
Style/NumericPredicate:
  EnforcedStyle: comparison
Style/PredicateName:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/MultilineMethodCallIndentation:
  EnforcedStyle: aligned
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
Style/ExtraSpacing:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/WordArray:
  Enabled: false
Documentation:
  Enabled: false
Metrics/ClassLength:
  Max: 400
